# Generated by Django 4.2.13 on 2024-06-29 18:32

from django.db import migrations, models
import main_window.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_list', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('load_img', models.ImageField(upload_to=main_window.models.custom_image_name, verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Информация')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('file_type', models.CharField(default='img', max_length=3, verbose_name='Тип файла')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Поле скрыто?')),
            ],
            options={
                'verbose_name': 'Список загруженных фотографий',
                'verbose_name_plural': 'Списки фотографий',
                'ordering': ['-create_time'],
            },
        ),
    ]
