# Generated by Django 4.2.13 on 2024-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Название')),
                ('load_img', models.ImageField(upload_to='main_window/db_content/img/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Информация')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Поле скрыто')),
            ],
            options={
                'verbose_name': 'Список загруженных фотографий',
                'verbose_name_plural': 'Списки фотографий',
                'ordering': ['-create_time'],
            },
        ),
    ]
