# Generated by Django 4.2.13 on 2024-06-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=20, verbose_name='Название')),
                ('path_field', models.CharField(max_length=20, verbose_name='Папка')),
                ('url_field', models.URLField(verbose_name='Адрес')),
                ('image_field', models.ImageField(upload_to='static/main_window/img/', verbose_name='Фото')),
                ('file_field', models.FileField(upload_to='static/main_window/videos/', verbose_name='Видео')),
                ('description_field', models.TextField(verbose_name='Информация')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Время загрузки')),
            ],
        ),
    ]
