# Generated by Django 4.2.13 on 2024-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdb',
            name='file_field',
            field=models.FileField(upload_to='main_window/db_content/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='contentdb',
            name='image_field',
            field=models.ImageField(upload_to='main_window/db_content/img/', verbose_name='Фото'),
        ),
    ]
