# Generated by Django 4.2.13 on 2024-06-27 17:46

from django.db import migrations, models
import main_window.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoscontent',
            name='file_type',
            field=models.CharField(default='img', max_length=3, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='photoscontent',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Поле скрыто?'),
        ),
        migrations.AlterField(
            model_name='photoscontent',
            name='load_img',
            field=models.ImageField(upload_to=main_window.models.custom_image_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photoscontent',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='Имя пользователя'),
        ),
    ]
