# Generated by Django 4.2.13 on 2024-06-26 20:52

from django.db import migrations, models
import main_window.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0003_photoscontent_delete_contentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoscontent',
            name='load_img',
            field=models.ImageField(storage=main_window.models.UUIDFileStorage(), upload_to='main_window/db_content/img/', verbose_name='Фото'),
        ),
    ]
